import { getDataSource } from '~~/server/utils/db'
import { DocumentSchema } from '~~/server/entities/document.entity'
import { AdministrationRunSchema } from '~~/server/entities/administration-run.entity'
import {
  AdministrationSchema,
  AdministrationStepSchema,
} from '~~/server/entities/administration.entity'
import { TemplateSchema, TemplateVersionSchema } from '~~/server/entities/template.entity'
import {
  ComponentSchema,
  ComponentDataRequirementSchema,
  ComponentVersionSchema,
} from '~~/server/entities/component.entity'
import { TemplateBindingSchema } from '~~/server/entities/template-binding.entity'
import { UserSchema } from '~~/server/entities/user.entity'
import { parseResolvedPins, parseStepDataMap } from '~~/server/utils/run-helpers'
import { collectPlacements, parseTreeInput } from '~~/server/utils/composition-tree'
import {
  driftInfo,
  driftLabel,
  parseSnapshot,
  sanitizeDocumentHtml,
  summarizeSnapshot,
  validateSnapshot,
} from '~~/server/utils/document-helpers'
import type { DocumentQueryInput } from '~~/server/dto/documents.dto'

function httpError(statusCode: number, message: string, data?: unknown): Error {
  return Object.assign(new Error(message), { statusCode, data })
}

const sortableFields = ['id', 'runId', 'administrationId', 'templateVersion', 'createdAt']

function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

async function isAdminUser(userId: number): Promise<boolean> {
  const ds = await getDataSource()
  const user: any = await ds.getRepository(UserSchema).findOne({ where: { id: userId } })
  const roles: any[] = user?.roles ?? []
  return roles.some((r) => r.roleName === 'Admin' || r.roleName === 'Super Admin')
}

async function assertDocumentAccess(doc: any, userId: number) {
  if (doc.createdBy === userId) return
  if (await isAdminUser(userId)) return
  throw httpError(403, 'You can only access your own documents')
}

/**
 * HTML-first interim renderer (Task 19). Assembles a deterministic
 * standalone document from the frozen snapshot so old documents render
 * byte-stable forever. Task 20 replaces this body with the real
 * rendering engine; the snapshot + storage contract is unchanged.
 */
function assembleIssueHtml(input: {
  administrationName: string
  templateName: string
  templateVersion: number
  stepName: string
  stepData: Record<string, unknown>
  issuedAt: Date
}): string {
  const rows = Object.entries(input.stepData ?? {})
    .map(([key, value]) => `<tr><td>${escapeHtml(key)}</td><td>${escapeHtml(JSON.stringify(value))}</td></tr>`)
    .join('')
  const raw =
    `<!DOCTYPE html><html><head><meta charset="utf-8">` +
    `<title>${escapeHtml(input.administrationName)} — ${escapeHtml(input.templateName)}</title></head>` +
    `<body><h1>${escapeHtml(input.administrationName)}</h1>` +
    `<p>${escapeHtml(input.templateName)} · template v${input.templateVersion} · step “${escapeHtml(input.stepName)}”</p>` +
    `<p>Issued ${escapeHtml(input.issuedAt.toISOString())}</p>` +
    `<table><thead><tr><th>Field</th><th>Value</th></tr></thead><tbody>${rows}</tbody></table>` +
    `<p>Generated by BMS — immutable snapshot document</p></body></html>`
  return sanitizeDocumentHtml(raw) ?? raw
}

async function enrich(doc: any) {
  const ds = await getDataSource()
  const administration: any = doc.administrationId
    ? await ds.getRepository(AdministrationSchema).findOne({ where: { id: doc.administrationId } })
    : null
  const template: any = doc.templateId
    ? await ds.getRepository(TemplateSchema).findOne({ where: { id: doc.templateId } })
    : null
  const creator: any = doc.createdBy
    ? await ds.getRepository(UserSchema).findOne({ where: { id: doc.createdBy } })
    : null
  const drift = driftInfo(doc.templateVersion, template?.version ?? null)
  const templateName = template?.name ?? (doc.templateId != null ? `Template #${doc.templateId}` : null)
  return {
    ...doc,
    administrationName: administration?.name ?? null,
    templateName,
    currentTemplateVersion: drift.current,
    drifted: drift.drifted,
    driftBadge: driftLabel(drift),
    createdByName: creator ? `${creator.firstName ?? ''} ${creator.lastName ?? ''}`.trim() || creator.username : null,
    title: `${administration?.name ?? `Administration #${doc.administrationId}`} — ${templateName ?? 'No template'} (run #${doc.runId})`,
  }
}

async function buildSnapshot(run: any, step: any, pinVersion: number, issuedBy: number | null) {
  const ds = await getDataSource()
  const dataMap = parseStepDataMap(run.stepData)
  const templateVersionRow: any = await ds.getRepository(TemplateVersionSchema).findOne({
    where: { templateId: step.templateId, version: pinVersion },
  })
  if (!templateVersionRow) {
    throw httpError(422, `Step "${step.name}" pins template #${step.templateId} v${pinVersion}, which has no frozen snapshot`, {
      code: 'TEMPLATE_SNAPSHOT_MISSING',
    })
  }

  const { nodes } = parseTreeInput(templateVersionRow.content)
  const placements = Array.isArray(nodes) ? collectPlacements(nodes as any) : []
  const componentSnapshots: any[] = []
  for (const placement of placements) {
    const component: any = await ds.getRepository(ComponentSchema).findOne({ where: { id: placement.componentId } })
    if (!component) continue
    const pinned = placement.componentVersion ?? component.version
    const versionRow: any = await ds.getRepository(ComponentVersionSchema).findOne({
      where: { componentId: component.id, version: pinned },
    })
    let requirements: any[] = []
    try {
      requirements = versionRow ? JSON.parse(versionRow.requirements) : []
    } catch {
      requirements = []
    }
    if (!versionRow) {
      const live: any[] = await ds.getRepository(ComponentDataRequirementSchema).find({ where: { componentId: component.id } })
      requirements = live.map((r) => ({ name: r.name, type: r.type }))
    }
    componentSnapshots.push({
      nodeId: placement.nodeId,
      componentId: component.id,
      componentName: component.name,
      version: versionRow?.version ?? pinned,
      content: versionRow?.content ?? component.content,
      looping: versionRow?.looping ?? component.looping,
      requirements,
    })
  }

  const bindings: any[] = await ds
    .getRepository(TemplateBindingSchema)
    .createQueryBuilder('b')
    .where('b."templateId" = :id', { id: step.templateId })
    .getMany()

  const snapshot = {
    runInput: dataMap[String(step.id)] ?? { fields: {}, rowSelections: {}, manualInputs: {} },
    templateContent: templateVersionRow.content,
    componentSnapshots,
    bindings,
    resolvedPins: parseResolvedPins(run.resolvedPins),
    systemContext: {
      runId: run.id,
      administrationId: run.administrationId,
      administrationVersion: run.administrationVersion,
      stepId: step.id,
      stepName: step.name,
      stepOrder: step.order,
      issuedAt: new Date().toISOString(),
      issuedBy,
    },
  }
  const check = validateSnapshot(snapshot)
  if (!check.valid) {
    throw httpError(422, `Document snapshot incomplete (missing: ${check.missing.join(', ')})`, {
      code: 'SNAPSHOT_INCOMPLETE',
      missing: check.missing,
    })
  }
  return snapshot
}

export const DocumentsService = {
  /**
   * REQ-004/BR-005: filterable browse. Non-admins are scoped to their own
   * documents (server-side `createdBy` filter); admins see all and may
   * filter by `createdBy`.
   */
  async findAll(query: DocumentQueryInput, userId: number) {
    const ds = await getDataSource()
    const admin = await isAdminUser(userId)
    const qb = ds.getRepository(DocumentSchema).createQueryBuilder('doc')

    if (!admin) qb.where('doc.createdBy = :userId', { userId })
    else qb.where('1 = 1')

    if (query.administrationId) qb.andWhere('doc.administrationId = :adminId', { adminId: query.administrationId })
    if (admin && query.createdBy) qb.andWhere('doc.createdBy = :createdBy', { createdBy: query.createdBy })
    if (query.startDate) qb.andWhere('doc.createdAt >= :startDate', { startDate: query.startDate })
    if (query.endDate) qb.andWhere('doc.createdAt <= :endDate', { endDate: query.endDate })
    if (query.search) {
      const like = `%${query.search}%`
      if (query.searchField === 'outputHtml') {
        qb.andWhere('doc.outputHtml LIKE :search', { search: like })
      } else {
        const matched: any[] = await ds
          .getRepository(AdministrationSchema)
          .createQueryBuilder('administration')
          .where('administration.name LIKE :search', { search: like })
          .getMany()
        const ids = matched.map((a) => a.id)
        if (ids.length > 0) {
          qb.andWhere('(doc.outputHtml LIKE :search OR doc.administrationId IN (:...ids))', { search: like, ids })
        } else {
          qb.andWhere('doc.outputHtml LIKE :search', { search: like })
        }
      }
    }
    if (sortableFields.includes(query.sortBy)) qb.orderBy(`doc.${query.sortBy}`, query.sortOrder)

    const total = await qb.getCount()
    const rows = await qb.skip((query.page - 1) * query.limit).take(query.limit).getMany()
    const data = await Promise.all(rows.map(enrich))
    return { data, total, page: query.page, limit: query.limit, totalPages: Math.ceil(total / query.limit) }
  },

  /** REQ-004: metadata + snapshot summary + pins (+ HTML unless `meta=1`). */
  async findOne(id: number, userId: number, metaOnly = false) {
    const ds = await getDataSource()
    const doc: any = await ds.getRepository(DocumentSchema).findOne({ where: { id } })
    if (!doc) throw httpError(404, 'Document not found')
    await assertDocumentAccess(doc, userId)
    const snapshot = parseSnapshot(doc.dataSnapshot)
    const enriched = await enrich(doc)
    return {
      ...enriched,
      snapshotSummary: summarizeSnapshot(snapshot),
      pins: (snapshot as any)?.resolvedPins ?? [],
      snapshot: metaOnly ? undefined : snapshot,
      outputHtml: metaOnly ? undefined : doc.outputHtml,
    }
  },

  async getHtml(id: number, userId: number): Promise<string> {
    const ds = await getDataSource()
    const doc: any = await ds.getRepository(DocumentSchema).findOne({ where: { id } })
    if (!doc) throw httpError(404, 'Document not found')
    await assertDocumentAccess(doc, userId)
    if (!doc.outputHtml) throw httpError(404, 'Rendered HTML is still pending for this document', { code: 'RENDER_PENDING' })
    return doc.outputHtml
  },

  /** PDF download info (BR-003); HTML-first interim leaves this empty until Task 20 fills it. */
  async getPdf(id: number, userId: number) {
    const ds = await getDataSource()
    const doc: any = await ds.getRepository(DocumentSchema).findOne({ where: { id } })
    if (!doc) throw httpError(404, 'Document not found')
    await assertDocumentAccess(doc, userId)
    if (!doc.outputFilePath) {
      throw httpError(404, 'PDF not rendered yet — HTML preview is available', { code: 'PDF_PENDING' })
    }
    const enriched = await enrich(doc)
    return { filePath: doc.outputFilePath, administrationName: enriched.administrationName }
  },

  /**
   * REQ-005: re-issue from the SAME snapshot against the SAME pinned
   * versions creates a NEW row linked via `replacesId` — the original is
   * never mutated. Admin-gated.
   */
  async reissue(id: number, userId: number) {
    if (!(await isAdminUser(userId))) throw httpError(403, 'Only admins can re-issue documents')
    const ds = await getDataSource()
    const original: any = await ds.getRepository(DocumentSchema).findOne({ where: { id } })
    if (!original) throw httpError(404, 'Document not found')
    const snapshot: any = parseSnapshot(original.dataSnapshot)
    if (!snapshot) throw httpError(422, 'Original snapshot is unreadable — cannot re-issue', { code: 'SNAPSHOT_CORRUPT' })

    const administration: any = await ds.getRepository(AdministrationSchema).findOne({
      where: { id: original.administrationId },
    })
    const template: any = original.templateId
      ? await ds.getRepository(TemplateSchema).findOne({ where: { id: original.templateId } })
      : null
    const html = assembleIssueHtml({
      administrationName: administration?.name ?? `Administration #${original.administrationId}`,
      templateName: template?.name ?? `Template #${original.templateId}`,
      templateVersion: original.templateVersion,
      stepName: snapshot.systemContext?.stepName ?? 'Step',
      stepData: snapshot.runInput ?? {},
      issuedAt: new Date(),
    })

    const repo = ds.getRepository(DocumentSchema)
    const saved: any = await repo.save(
      repo.create({
        runId: original.runId,
        administrationId: original.administrationId,
        stepId: original.stepId,
        templateId: original.templateId,
        templateVersion: original.templateVersion,
        dataSnapshot: original.dataSnapshot,
        outputHtml: html,
        outputFilePath: null,
        replacesId: original.id,
        createdBy: userId,
      }),
    )
    return enrich(saved)
  },

  /** REQ-006: explicit admin purge only (no update API exists). */
  async purge(id: number, userId: number) {
    if (!(await isAdminUser(userId))) throw httpError(403, 'Only admins can purge documents')
    const ds = await getDataSource()
    const repo = ds.getRepository(DocumentSchema)
    const doc: any = await repo.findOne({ where: { id } })
    if (!doc) throw httpError(404, 'Document not found')
    await repo.remove(doc)
    return { message: 'Document purged' }
  },

  /**
   * System-internal issuance for the run-complete hook (REQ-001/BR-004):
   * one document per template-step, ordered by step order, sharing `runId`.
   */
  async issueDocumentsForRun(runId: number): Promise<number[]> {
    const ds = await getDataSource()
    const run: any = await ds.getRepository(AdministrationRunSchema).findOne({ where: { id: runId } })
    if (!run) throw httpError(404, 'Run not found')
    const steps: any[] = await ds
      .getRepository(AdministrationStepSchema)
      .createQueryBuilder('step')
      .where('step.administrationId = :id', { id: run.administrationId })
      .orderBy('step.order', 'ASC')
      .getMany()
    const administration: any = await ds.getRepository(AdministrationSchema).findOne({
      where: { id: run.administrationId },
    })
    const pins = parseResolvedPins(run.resolvedPins)
    const pinByStep = new Map<number, string>(pins.map((p: any) => [p.stepId, p.version]))

    const repo = ds.getRepository(DocumentSchema)
    const ids: number[] = []
    for (const step of steps) {
      if (step.templateId == null) continue
      const rawPin = pinByStep.get(step.id) ?? step.templateVersion
      const pinVersion = Number(rawPin)
      if (!Number.isInteger(pinVersion) || pinVersion < 1) {
        throw httpError(422, `Step "${step.name}" has no frozen template version — cannot issue a document`, {
          code: 'PIN_UNRESOLVED',
        })
      }
      const snapshot = await buildSnapshot(run, step, pinVersion, run.startedBy)
      const template: any = await ds.getRepository(TemplateSchema).findOne({ where: { id: step.templateId } })
      const html = assembleIssueHtml({
        administrationName: administration?.name ?? `Administration #${run.administrationId}`,
        templateName: template?.name ?? `Template #${step.templateId}`,
        templateVersion: pinVersion,
        stepName: step.name,
        stepData: (snapshot as any).runInput ?? {},
        issuedAt: new Date(),
      })
      const saved: any = await repo.save(
        repo.create({
          runId: run.id,
          administrationId: run.administrationId,
          stepId: step.id,
          templateId: step.templateId,
          templateVersion: pinVersion,
          dataSnapshot: JSON.stringify(snapshot),
          outputHtml: html,
          outputFilePath: null,
          replacesId: null,
          createdBy: run.startedBy,
        }),
      )
      ids.push(saved.id)
    }
    return ids
  },
}
