import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1788914913928 implements MigrationInterface {
    name = 'Baseline1788914913928'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "firstName" varchar NOT NULL, "lastName" varchar NOT NULL, "username" varchar NOT NULL, "email" varchar NOT NULL, "password" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "roleName" varchar NOT NULL, "description" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_992f24b9d80eb1312440ca577f1" UNIQUE ("roleName"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "permissionName" varchar NOT NULL, "description" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_56583ae1f32a17a0925f4a5f893" UNIQUE ("permissionName"))`);
        await queryRunner.query(`CREATE TABLE "permission_methods" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "method" varchar NOT NULL, "permissionId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "permission_urls" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "url" varchar NOT NULL, "permissionId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "guards" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "guardName" varchar NOT NULL, "description" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_23c3a5d66f0dd955867d576b07e" UNIQUE ("guardName"))`);
        await queryRunner.query(`CREATE TABLE "guard_urls" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "url" varchar NOT NULL, "type" varchar NOT NULL, "guardId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "userId" integer, "action" varchar NOT NULL, "entity" varchar NOT NULL, "entityId" integer, "description" text, "metadata" text, "ipAddress" varchar, "userAgent" varchar, "level" varchar(20) NOT NULL DEFAULT ('INFO'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "settings" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" varchar NOT NULL, "value" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c8639b7626fa94ba8265628f214" UNIQUE ("key"))`);
        await queryRunner.query(`CREATE TABLE "global_tables" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(64) NOT NULL, "displayName" varchar(100) NOT NULL, "menuOrder" integer, "menuIcon" varchar(32), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_48ae1925ab97ec97752799a19fe" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "global_table_columns" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "globalTableId" integer NOT NULL, "name" varchar(64) NOT NULL, "displayName" varchar(100) NOT NULL, "type" varchar(32) NOT NULL, "defaultValue" varchar, "required" boolean NOT NULL DEFAULT (0), "searchable" boolean NOT NULL DEFAULT (0), "orderable" boolean NOT NULL DEFAULT (0), "position" integer NOT NULL, "options" text, "format" varchar(32), "expression" text, "dependencies" text, "relationTableId" integer, "relationConfig" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_GLOBAL_TABLE_COLUMN_TABLE_ID_NAME" ON "global_table_columns" ("globalTableId", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_GLOBAL_TABLE_COLUMN_TABLE_ID_POSITION" ON "global_table_columns" ("globalTableId", "position") `);
        await queryRunner.query(`CREATE INDEX "IDX_GLOBAL_TABLE_COLUMN_RELATION_TABLE_ID" ON "global_table_columns" ("relationTableId") `);
        await queryRunner.query(`CREATE TABLE "global_table_rows" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "globalTableId" integer NOT NULL, "values" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_GLOBAL_TABLE_ROWS_TABLE_ID" ON "global_table_rows" ("globalTableId", "id") `);
        await queryRunner.query(`CREATE TABLE "components" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(100) NOT NULL, "content" text, "looping" boolean NOT NULL DEFAULT (0), "preview" text, "version" integer NOT NULL DEFAULT (1), "status" varchar(16) NOT NULL DEFAULT ('draft'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_673dc1c412adfb5b54ec419224e" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_COMPONENT_NAME" ON "components" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_COMPONENT_STATUS" ON "components" ("status") `);
        await queryRunner.query(`CREATE TABLE "component_data_requirements" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "componentId" integer NOT NULL, "name" varchar(64) NOT NULL, "type" varchar(16) NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_COMPONENT_REQUIREMENT_COMPONENT_ID_NAME" ON "component_data_requirements" ("componentId", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_COMPONENT_REQUIREMENT_COMPONENT_ID" ON "component_data_requirements" ("componentId") `);
        await queryRunner.query(`CREATE TABLE "component_versions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "componentId" integer NOT NULL, "version" integer NOT NULL, "content" text, "looping" boolean NOT NULL DEFAULT (0), "requirements" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_COMPONENT_VERSION_COMPONENT_ID_VERSION" ON "component_versions" ("componentId", "version") `);
        await queryRunner.query(`CREATE INDEX "IDX_COMPONENT_VERSION_COMPONENT_ID" ON "component_versions" ("componentId") `);
        await queryRunner.query(`CREATE TABLE "templates" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(100) NOT NULL, "description" text, "content" text, "version" integer NOT NULL DEFAULT (0), "status" varchar(16) NOT NULL DEFAULT ('draft'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_5624219dd33b4644599d4d4b231" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_TEMPLATE_NAME" ON "templates" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_TEMPLATE_STATUS" ON "templates" ("status") `);
        await queryRunner.query(`CREATE TABLE "template_versions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "templateId" integer NOT NULL, "version" integer NOT NULL, "content" text NOT NULL, "publishedBy" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_TEMPLATE_VERSION_TEMPLATE_ID_VERSION" ON "template_versions" ("templateId", "version") `);
        await queryRunner.query(`CREATE INDEX "IDX_TEMPLATE_VERSION_TEMPLATE_ID" ON "template_versions" ("templateId") `);
        await queryRunner.query(`CREATE TABLE "template_bindings" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "templateId" integer NOT NULL, "placementId" varchar(64) NOT NULL, "componentId" integer NOT NULL, "requirementName" varchar(64) NOT NULL, "source" varchar(16) NOT NULL, "sourceRef" varchar(255), "literalValue" text, "expression" text, "status" varchar(16) NOT NULL DEFAULT ('bound'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_TEMPLATE_BINDING_TEMPLATE_ID" ON "template_bindings" ("templateId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_TEMPLATE_BINDING_TEMPLATE_PLACEMENT_REQUIREMENT" ON "template_bindings" ("templateId", "placementId", "requirementName") `);
        await queryRunner.query(`CREATE INDEX "IDX_TEMPLATE_BINDING_COMPONENT_ID" ON "template_bindings" ("componentId") `);
        await queryRunner.query(`CREATE TABLE "administrations" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(100) NOT NULL, "description" text, "status" varchar(16) NOT NULL DEFAULT ('draft'), "version" integer NOT NULL DEFAULT (0), "menuOrder" integer, "menuIcon" varchar(32), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_bd5ff627a9fdb684f85cfeffd78" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ADMINISTRATION_NAME" ON "administrations" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_ADMINISTRATION_STATUS" ON "administrations" ("status") `);
        await queryRunner.query(`CREATE TABLE "administration_steps" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "administrationId" integer NOT NULL, "order" integer NOT NULL, "name" varchar(100) NOT NULL, "templateId" integer, "templateVersion" varchar(16), "fields" text)`);
        await queryRunner.query(`CREATE INDEX "IDX_ADMIN_STEP_ADMIN_ID" ON "administration_steps" ("administrationId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ADMIN_STEP_ADMIN_ID_ORDER" ON "administration_steps" ("administrationId", "order") `);
        await queryRunner.query(`CREATE INDEX "IDX_ADMIN_STEP_TEMPLATE_ID" ON "administration_steps" ("templateId") `);
        await queryRunner.query(`CREATE TABLE "administration_versions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "administrationId" integer NOT NULL, "version" integer NOT NULL, "steps" text NOT NULL, "publishedBy" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ADMIN_VERSION_ADMIN_ID_VERSION" ON "administration_versions" ("administrationId", "version") `);
        await queryRunner.query(`CREATE INDEX "IDX_ADMIN_VERSION_ADMIN_ID" ON "administration_versions" ("administrationId") `);
        await queryRunner.query(`CREATE TABLE "administration_runs" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "administrationId" integer NOT NULL, "administrationVersion" integer NOT NULL DEFAULT (0), "resolvedPins" text NOT NULL, "stepData" text NOT NULL, "status" varchar(16) NOT NULL DEFAULT ('in_progress'), "startedBy" integer, "startedAt" datetime, "completedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_ADMIN_RUN_ADMIN_ID_STATUS" ON "administration_runs" ("administrationId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ADMIN_RUN_STARTED_BY" ON "administration_runs" ("startedBy") `);
        await queryRunner.query(`CREATE TABLE "documents" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "runId" integer NOT NULL, "administrationId" integer NOT NULL, "stepId" integer, "templateId" integer, "templateVersion" integer NOT NULL, "dataSnapshot" text NOT NULL, "outputHtml" text, "outputFilePath" varchar(500), "replacesId" integer, "createdBy" integer, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_DOCUMENT_ADMIN_ID_CREATED_AT" ON "documents" ("administrationId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_DOCUMENT_RUN_ID" ON "documents" ("runId") `);
        await queryRunner.query(`CREATE TABLE "users_roles" ("userId" integer NOT NULL, "roleId" integer NOT NULL, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_776b7cf9330802e5ef5a8fb18d" ON "users_roles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4fb14631257670efa14b15a3d8" ON "users_roles" ("roleId") `);
        await queryRunner.query(`CREATE TABLE "roles_guards" ("roleId" integer NOT NULL, "guardId" integer NOT NULL, PRIMARY KEY ("roleId", "guardId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a9f80847d36d65c50283e0ee63" ON "roles_guards" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ffb0b49706d51042942ef58f0" ON "roles_guards" ("guardId") `);
        await queryRunner.query(`CREATE TABLE "roles_permissions" ("roleId" integer NOT NULL, "permissionId" integer NOT NULL, PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_28bf280551eb9aa82daf1e156d" ON "roles_permissions" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_31cf5c31d0096f706e3ba3b1e8" ON "roles_permissions" ("permissionId") `);
        await queryRunner.query(`CREATE TABLE "temporary_permission_methods" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "method" varchar NOT NULL, "permissionId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_f503cfaea4b2943ee8203a49c21" FOREIGN KEY ("permissionId") REFERENCES "permissions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_permission_methods"("id", "method", "permissionId", "createdAt") SELECT "id", "method", "permissionId", "createdAt" FROM "permission_methods"`);
        await queryRunner.query(`DROP TABLE "permission_methods"`);
        await queryRunner.query(`ALTER TABLE "temporary_permission_methods" RENAME TO "permission_methods"`);
        await queryRunner.query(`CREATE TABLE "temporary_permission_urls" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "url" varchar NOT NULL, "permissionId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_0e8fb821f6daf931352d1702a23" FOREIGN KEY ("permissionId") REFERENCES "permissions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_permission_urls"("id", "url", "permissionId", "createdAt") SELECT "id", "url", "permissionId", "createdAt" FROM "permission_urls"`);
        await queryRunner.query(`DROP TABLE "permission_urls"`);
        await queryRunner.query(`ALTER TABLE "temporary_permission_urls" RENAME TO "permission_urls"`);
        await queryRunner.query(`CREATE TABLE "temporary_guard_urls" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "url" varchar NOT NULL, "type" varchar NOT NULL, "guardId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_4ff76564f78abb2eff99792f75a" FOREIGN KEY ("guardId") REFERENCES "guards" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_guard_urls"("id", "url", "type", "guardId", "createdAt") SELECT "id", "url", "type", "guardId", "createdAt" FROM "guard_urls"`);
        await queryRunner.query(`DROP TABLE "guard_urls"`);
        await queryRunner.query(`ALTER TABLE "temporary_guard_urls" RENAME TO "guard_urls"`);
        await queryRunner.query(`CREATE TABLE "temporary_activity_logs" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "userId" integer, "action" varchar NOT NULL, "entity" varchar NOT NULL, "entityId" integer, "description" text, "metadata" text, "ipAddress" varchar, "userAgent" varchar, "level" varchar(20) NOT NULL DEFAULT ('INFO'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_597e6df96098895bf19d4b5ea45" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_activity_logs"("id", "userId", "action", "entity", "entityId", "description", "metadata", "ipAddress", "userAgent", "level", "createdAt") SELECT "id", "userId", "action", "entity", "entityId", "description", "metadata", "ipAddress", "userAgent", "level", "createdAt" FROM "activity_logs"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`ALTER TABLE "temporary_activity_logs" RENAME TO "activity_logs"`);
        await queryRunner.query(`DROP INDEX "IDX_GLOBAL_TABLE_ROWS_TABLE_ID"`);
        await queryRunner.query(`CREATE TABLE "temporary_global_table_rows" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "globalTableId" integer NOT NULL, "values" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_ca024bcf16f361807a489bd96bf" FOREIGN KEY ("globalTableId") REFERENCES "global_tables" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_global_table_rows"("id", "globalTableId", "values", "createdAt", "updatedAt") SELECT "id", "globalTableId", "values", "createdAt", "updatedAt" FROM "global_table_rows"`);
        await queryRunner.query(`DROP TABLE "global_table_rows"`);
        await queryRunner.query(`ALTER TABLE "temporary_global_table_rows" RENAME TO "global_table_rows"`);
        await queryRunner.query(`CREATE INDEX "IDX_GLOBAL_TABLE_ROWS_TABLE_ID" ON "global_table_rows" ("globalTableId", "id") `);
        await queryRunner.query(`DROP INDEX "IDX_776b7cf9330802e5ef5a8fb18d"`);
        await queryRunner.query(`DROP INDEX "IDX_4fb14631257670efa14b15a3d8"`);
        await queryRunner.query(`CREATE TABLE "temporary_users_roles" ("userId" integer NOT NULL, "roleId" integer NOT NULL, CONSTRAINT "FK_776b7cf9330802e5ef5a8fb18dc" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_4fb14631257670efa14b15a3d86" FOREIGN KEY ("roleId") REFERENCES "roles" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`INSERT INTO "temporary_users_roles"("userId", "roleId") SELECT "userId", "roleId" FROM "users_roles"`);
        await queryRunner.query(`DROP TABLE "users_roles"`);
        await queryRunner.query(`ALTER TABLE "temporary_users_roles" RENAME TO "users_roles"`);
        await queryRunner.query(`CREATE INDEX "IDX_776b7cf9330802e5ef5a8fb18d" ON "users_roles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4fb14631257670efa14b15a3d8" ON "users_roles" ("roleId") `);
        await queryRunner.query(`DROP INDEX "IDX_a9f80847d36d65c50283e0ee63"`);
        await queryRunner.query(`DROP INDEX "IDX_8ffb0b49706d51042942ef58f0"`);
        await queryRunner.query(`CREATE TABLE "temporary_roles_guards" ("roleId" integer NOT NULL, "guardId" integer NOT NULL, CONSTRAINT "FK_a9f80847d36d65c50283e0ee63c" FOREIGN KEY ("roleId") REFERENCES "roles" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_8ffb0b49706d51042942ef58f0c" FOREIGN KEY ("guardId") REFERENCES "guards" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("roleId", "guardId"))`);
        await queryRunner.query(`INSERT INTO "temporary_roles_guards"("roleId", "guardId") SELECT "roleId", "guardId" FROM "roles_guards"`);
        await queryRunner.query(`DROP TABLE "roles_guards"`);
        await queryRunner.query(`ALTER TABLE "temporary_roles_guards" RENAME TO "roles_guards"`);
        await queryRunner.query(`CREATE INDEX "IDX_a9f80847d36d65c50283e0ee63" ON "roles_guards" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ffb0b49706d51042942ef58f0" ON "roles_guards" ("guardId") `);
        await queryRunner.query(`DROP INDEX "IDX_28bf280551eb9aa82daf1e156d"`);
        await queryRunner.query(`DROP INDEX "IDX_31cf5c31d0096f706e3ba3b1e8"`);
        await queryRunner.query(`CREATE TABLE "temporary_roles_permissions" ("roleId" integer NOT NULL, "permissionId" integer NOT NULL, CONSTRAINT "FK_28bf280551eb9aa82daf1e156d9" FOREIGN KEY ("roleId") REFERENCES "roles" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_31cf5c31d0096f706e3ba3b1e82" FOREIGN KEY ("permissionId") REFERENCES "permissions" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`INSERT INTO "temporary_roles_permissions"("roleId", "permissionId") SELECT "roleId", "permissionId" FROM "roles_permissions"`);
        await queryRunner.query(`DROP TABLE "roles_permissions"`);
        await queryRunner.query(`ALTER TABLE "temporary_roles_permissions" RENAME TO "roles_permissions"`);
        await queryRunner.query(`CREATE INDEX "IDX_28bf280551eb9aa82daf1e156d" ON "roles_permissions" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_31cf5c31d0096f706e3ba3b1e8" ON "roles_permissions" ("permissionId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_31cf5c31d0096f706e3ba3b1e8"`);
        await queryRunner.query(`DROP INDEX "IDX_28bf280551eb9aa82daf1e156d"`);
        await queryRunner.query(`ALTER TABLE "roles_permissions" RENAME TO "temporary_roles_permissions"`);
        await queryRunner.query(`CREATE TABLE "roles_permissions" ("roleId" integer NOT NULL, "permissionId" integer NOT NULL, PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`INSERT INTO "roles_permissions"("roleId", "permissionId") SELECT "roleId", "permissionId" FROM "temporary_roles_permissions"`);
        await queryRunner.query(`DROP TABLE "temporary_roles_permissions"`);
        await queryRunner.query(`CREATE INDEX "IDX_31cf5c31d0096f706e3ba3b1e8" ON "roles_permissions" ("permissionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_28bf280551eb9aa82daf1e156d" ON "roles_permissions" ("roleId") `);
        await queryRunner.query(`DROP INDEX "IDX_8ffb0b49706d51042942ef58f0"`);
        await queryRunner.query(`DROP INDEX "IDX_a9f80847d36d65c50283e0ee63"`);
        await queryRunner.query(`ALTER TABLE "roles_guards" RENAME TO "temporary_roles_guards"`);
        await queryRunner.query(`CREATE TABLE "roles_guards" ("roleId" integer NOT NULL, "guardId" integer NOT NULL, PRIMARY KEY ("roleId", "guardId"))`);
        await queryRunner.query(`INSERT INTO "roles_guards"("roleId", "guardId") SELECT "roleId", "guardId" FROM "temporary_roles_guards"`);
        await queryRunner.query(`DROP TABLE "temporary_roles_guards"`);
        await queryRunner.query(`CREATE INDEX "IDX_8ffb0b49706d51042942ef58f0" ON "roles_guards" ("guardId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9f80847d36d65c50283e0ee63" ON "roles_guards" ("roleId") `);
        await queryRunner.query(`DROP INDEX "IDX_4fb14631257670efa14b15a3d8"`);
        await queryRunner.query(`DROP INDEX "IDX_776b7cf9330802e5ef5a8fb18d"`);
        await queryRunner.query(`ALTER TABLE "users_roles" RENAME TO "temporary_users_roles"`);
        await queryRunner.query(`CREATE TABLE "users_roles" ("userId" integer NOT NULL, "roleId" integer NOT NULL, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`INSERT INTO "users_roles"("userId", "roleId") SELECT "userId", "roleId" FROM "temporary_users_roles"`);
        await queryRunner.query(`DROP TABLE "temporary_users_roles"`);
        await queryRunner.query(`CREATE INDEX "IDX_4fb14631257670efa14b15a3d8" ON "users_roles" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_776b7cf9330802e5ef5a8fb18d" ON "users_roles" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_GLOBAL_TABLE_ROWS_TABLE_ID"`);
        await queryRunner.query(`ALTER TABLE "global_table_rows" RENAME TO "temporary_global_table_rows"`);
        await queryRunner.query(`CREATE TABLE "global_table_rows" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "globalTableId" integer NOT NULL, "values" text NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "global_table_rows"("id", "globalTableId", "values", "createdAt", "updatedAt") SELECT "id", "globalTableId", "values", "createdAt", "updatedAt" FROM "temporary_global_table_rows"`);
        await queryRunner.query(`DROP TABLE "temporary_global_table_rows"`);
        await queryRunner.query(`CREATE INDEX "IDX_GLOBAL_TABLE_ROWS_TABLE_ID" ON "global_table_rows" ("globalTableId", "id") `);
        await queryRunner.query(`ALTER TABLE "activity_logs" RENAME TO "temporary_activity_logs"`);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "userId" integer, "action" varchar NOT NULL, "entity" varchar NOT NULL, "entityId" integer, "description" text, "metadata" text, "ipAddress" varchar, "userAgent" varchar, "level" varchar(20) NOT NULL DEFAULT ('INFO'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "activity_logs"("id", "userId", "action", "entity", "entityId", "description", "metadata", "ipAddress", "userAgent", "level", "createdAt") SELECT "id", "userId", "action", "entity", "entityId", "description", "metadata", "ipAddress", "userAgent", "level", "createdAt" FROM "temporary_activity_logs"`);
        await queryRunner.query(`DROP TABLE "temporary_activity_logs"`);
        await queryRunner.query(`ALTER TABLE "guard_urls" RENAME TO "temporary_guard_urls"`);
        await queryRunner.query(`CREATE TABLE "guard_urls" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "url" varchar NOT NULL, "type" varchar NOT NULL, "guardId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "guard_urls"("id", "url", "type", "guardId", "createdAt") SELECT "id", "url", "type", "guardId", "createdAt" FROM "temporary_guard_urls"`);
        await queryRunner.query(`DROP TABLE "temporary_guard_urls"`);
        await queryRunner.query(`ALTER TABLE "permission_urls" RENAME TO "temporary_permission_urls"`);
        await queryRunner.query(`CREATE TABLE "permission_urls" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "url" varchar NOT NULL, "permissionId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "permission_urls"("id", "url", "permissionId", "createdAt") SELECT "id", "url", "permissionId", "createdAt" FROM "temporary_permission_urls"`);
        await queryRunner.query(`DROP TABLE "temporary_permission_urls"`);
        await queryRunner.query(`ALTER TABLE "permission_methods" RENAME TO "temporary_permission_methods"`);
        await queryRunner.query(`CREATE TABLE "permission_methods" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "method" varchar NOT NULL, "permissionId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "permission_methods"("id", "method", "permissionId", "createdAt") SELECT "id", "method", "permissionId", "createdAt" FROM "temporary_permission_methods"`);
        await queryRunner.query(`DROP TABLE "temporary_permission_methods"`);
        await queryRunner.query(`DROP INDEX "IDX_31cf5c31d0096f706e3ba3b1e8"`);
        await queryRunner.query(`DROP INDEX "IDX_28bf280551eb9aa82daf1e156d"`);
        await queryRunner.query(`DROP TABLE "roles_permissions"`);
        await queryRunner.query(`DROP INDEX "IDX_8ffb0b49706d51042942ef58f0"`);
        await queryRunner.query(`DROP INDEX "IDX_a9f80847d36d65c50283e0ee63"`);
        await queryRunner.query(`DROP TABLE "roles_guards"`);
        await queryRunner.query(`DROP INDEX "IDX_4fb14631257670efa14b15a3d8"`);
        await queryRunner.query(`DROP INDEX "IDX_776b7cf9330802e5ef5a8fb18d"`);
        await queryRunner.query(`DROP TABLE "users_roles"`);
        await queryRunner.query(`DROP INDEX "IDX_DOCUMENT_RUN_ID"`);
        await queryRunner.query(`DROP INDEX "IDX_DOCUMENT_ADMIN_ID_CREATED_AT"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP INDEX "IDX_ADMIN_RUN_STARTED_BY"`);
        await queryRunner.query(`DROP INDEX "IDX_ADMIN_RUN_ADMIN_ID_STATUS"`);
        await queryRunner.query(`DROP TABLE "administration_runs"`);
        await queryRunner.query(`DROP INDEX "IDX_ADMIN_VERSION_ADMIN_ID"`);
        await queryRunner.query(`DROP INDEX "IDX_ADMIN_VERSION_ADMIN_ID_VERSION"`);
        await queryRunner.query(`DROP TABLE "administration_versions"`);
        await queryRunner.query(`DROP INDEX "IDX_ADMIN_STEP_TEMPLATE_ID"`);
        await queryRunner.query(`DROP INDEX "IDX_ADMIN_STEP_ADMIN_ID_ORDER"`);
        await queryRunner.query(`DROP INDEX "IDX_ADMIN_STEP_ADMIN_ID"`);
        await queryRunner.query(`DROP TABLE "administration_steps"`);
        await queryRunner.query(`DROP INDEX "IDX_ADMINISTRATION_STATUS"`);
        await queryRunner.query(`DROP INDEX "IDX_ADMINISTRATION_NAME"`);
        await queryRunner.query(`DROP TABLE "administrations"`);
        await queryRunner.query(`DROP INDEX "IDX_TEMPLATE_BINDING_COMPONENT_ID"`);
        await queryRunner.query(`DROP INDEX "IDX_TEMPLATE_BINDING_TEMPLATE_PLACEMENT_REQUIREMENT"`);
        await queryRunner.query(`DROP INDEX "IDX_TEMPLATE_BINDING_TEMPLATE_ID"`);
        await queryRunner.query(`DROP TABLE "template_bindings"`);
        await queryRunner.query(`DROP INDEX "IDX_TEMPLATE_VERSION_TEMPLATE_ID"`);
        await queryRunner.query(`DROP INDEX "IDX_TEMPLATE_VERSION_TEMPLATE_ID_VERSION"`);
        await queryRunner.query(`DROP TABLE "template_versions"`);
        await queryRunner.query(`DROP INDEX "IDX_TEMPLATE_STATUS"`);
        await queryRunner.query(`DROP INDEX "IDX_TEMPLATE_NAME"`);
        await queryRunner.query(`DROP TABLE "templates"`);
        await queryRunner.query(`DROP INDEX "IDX_COMPONENT_VERSION_COMPONENT_ID"`);
        await queryRunner.query(`DROP INDEX "IDX_COMPONENT_VERSION_COMPONENT_ID_VERSION"`);
        await queryRunner.query(`DROP TABLE "component_versions"`);
        await queryRunner.query(`DROP INDEX "IDX_COMPONENT_REQUIREMENT_COMPONENT_ID"`);
        await queryRunner.query(`DROP INDEX "IDX_COMPONENT_REQUIREMENT_COMPONENT_ID_NAME"`);
        await queryRunner.query(`DROP TABLE "component_data_requirements"`);
        await queryRunner.query(`DROP INDEX "IDX_COMPONENT_STATUS"`);
        await queryRunner.query(`DROP INDEX "IDX_COMPONENT_NAME"`);
        await queryRunner.query(`DROP TABLE "components"`);
        await queryRunner.query(`DROP INDEX "IDX_GLOBAL_TABLE_ROWS_TABLE_ID"`);
        await queryRunner.query(`DROP TABLE "global_table_rows"`);
        await queryRunner.query(`DROP INDEX "IDX_GLOBAL_TABLE_COLUMN_RELATION_TABLE_ID"`);
        await queryRunner.query(`DROP INDEX "IDX_GLOBAL_TABLE_COLUMN_TABLE_ID_POSITION"`);
        await queryRunner.query(`DROP INDEX "IDX_GLOBAL_TABLE_COLUMN_TABLE_ID_NAME"`);
        await queryRunner.query(`DROP TABLE "global_table_columns"`);
        await queryRunner.query(`DROP TABLE "global_tables"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`DROP TABLE "guard_urls"`);
        await queryRunner.query(`DROP TABLE "guards"`);
        await queryRunner.query(`DROP TABLE "permission_urls"`);
        await queryRunner.query(`DROP TABLE "permission_methods"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
